// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Load .env.local first (dev convention), then fall back to .env. dotenv does
// not overwrite already-set keys, so .env.local takes precedence.
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config();
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
